### ISSUE TITLE
Add cooldowns to channel commands

### ISSUE THREAD

**Issue by Toby-Larone** [Toby-Larone/mimic#12]
**Is your feature request related to a problem? Please describe.**
There is currently no cooldown on channel commands.

**Describe the solution you'd like**
Cool downs should be added to `channels.edit`, `channels.add`, and `channels.remove`.
Cool down should be 5 seconds and scoped to the user.
Cooldowns should not send the cooldown message. If disparse has been updated (https://github.com/BoscoJared/disparse/issues/26), then the cooldown reaction should be sent.

**Comment by Kokoden** [comment]
Hey! Can I get this issue assigned to me please? 😄

**Comment by Toby-Larone** [comment]
Fixed with #13
